### PR TITLE
EKS with nodegroup

### PR DESCRIPTION
**Pull request by dpoirier**
This is a rewrite of the current EKS pull request to use a Nodegroup instead of setting up the instances ourselves.  This lets us simplify things quite a bit in terms of managing security groups etc. I've tested this by creating an EKS cluster on the Caktus account and deploying a hello world application to it.

I assumed we would not need the S3 buckets or logging that we otherwise set up when creating a stack for a specific application.

I did some refactoring as well to reduce duplication of code to set up things like policies and roles that were nearly identical across stacks.

### CODE REVIEW

**Comment by tobiasmcnulty** [comment]
FYI I am seeing a fair number of changes to the non-EKS stacks that might not be intentional (or maybe they are?). On the original `eks` branch the only changes are the removal of the SecretKey where it's not relevant, I think.

To generate this I ran `make` on `develop` and then copied that to `content.orig`. Then I removed the duplicate (versioned) files and the new EKS stacks to show just the changes between the old and new non-EKS stacks.

[non-eks-changes.txt](https://github.com/caktus/aws-web-stacks/files/4225761/non-eks-changes.txt)

**Comment by tobiasmcnulty** [comment]
(I'm going to temporarily change the base branch to `eks` to make it easier for me to review. Will switch back when done.)

**Comment by dpoirier** [comment]
@tobiasmcnulty I've pushed an update that corrects most of the unplanned changes to the resulting templates. See the commit message for a longer explanation.

**Comment by dpoirier** [comment]
I can simplify this a little bit once https://github.com/caktus/aws-web-stacks/pull/94 is merged. After updating Troposphere to the latest release that includes my fixes to Nodegroup, we won't need to subclass Nodegroup in aws-web-stacks.

**Pull request merged**
